CREATE SEQUENCE EXPORT_ID_SEQUENCE START 1;
CREATE SEQUENCE EVENT_ID_SEQUENCE START 1;

CREATE TABLE EXPORT_RUN (
	ID BIGINT,
	START_TIME TIMESTAMP,
	END_TIME TIMESTAMP,
	STATUS VARCHAR(50),
	
	PRIMARY KEY(ID)
);

CREATE TABLE KINDMAPPE_ID (
	ID BIGINT
);

CREATE TABLE KIND (
	ID BIGINT,
	EXPORT_ID BIGINT,
	TIMESTAMP TIMESTAMP,
	
	MASTERKIND_ID BIGINT,
	
	PRIMARY KEY(ID, EXPORT_ID),
    CONSTRAINT FK_EXPORT
    	FOREIGN KEY(EXPORT_ID)
        REFERENCES EXPORT_RUN(ID)
);

CREATE TABLE SORGEBERECHTIGTER (
    ID BIGINT,
    EXPORT_ID BIGINT,
    
    ANREDE VARCHAR(255),
    TITEL VARCHAR(255),
    VORNAME VARCHAR(255),
    NACHNAME VARCHAR(255),
    STRASSE VARCHAR(255),
    HAUSNUMMER VARCHAR(50),
    PLZ VARCHAR(20),
    ORT VARCHAR(255),
    LAND VARCHAR(255),
    TELEFON1 VARCHAR(50),
    TELEFON2 VARCHAR(50),
    EMAIL VARCHAR(255),
    AUSLAENDISCHEHERKUNFT BOOLEAN,
    NICHT_DEUTSCHSPRACHIGE_HERKUNFT BOOLEAN,
    ALLEIN_ERZIEHEND BOOLEAN,
    GEPLANTE_AUFNAHME_BERUFSTAETIGKEIT BOOLEAN,
    GEPLANTE_AUFNAHME_BERUFSTAETIGKEIT_AB VARCHAR(10),
    GEPLANT_AUFNAHME_AUSBILDUNG BOOLEAN,
    GEPLANT_AUFNAHME_AUSBILDUNG_AB VARCHAR(10),
    GEPLANT_AUFNAHME_STUDIUM BOOLEAN,
    GEPLANT_AUFNAHME_STUDIUM_AB VARCHAR(10),
    BERUFSTAETIG BOOLEAN,
    ERST_STUDIUM_AUSBILDUNG BOOLEAN,
    WOCHENARBEITSZEIT DOUBLE PRECISION,
    WOCHENARBEITSTAGE DOUBLE PRECISION,
    LAGE_DER_ARBEITSZEIT_ID INTEGER,
    ARBEITSUCHEND BOOLEAN,
    ARBEITSUCHEND_SEIT VARCHAR(10),
    
    PRIMARY KEY (ID, EXPORT_ID)
);

CREATE TABLE KINDDATEN (
	KIND_ID BIGINT,
	ID BIGINT,
	EXPORT_ID BIGINT,
	KINDAKTENTYP VARCHAR(50),
	
	VORNAME VARCHAR(255),
	NACHNAME VARCHAR(255),
	GEBURTSDATUM VARCHAR(255),
	geschlecht VARCHAR(50),
	pflegekind BOOLEAN,
	immunisierung_Masern VARCHAR(50),
	wohnhaft_Bei VARCHAR(50),
	familiensprache VARCHAR(255),
	weitere_Familiensprachen VARCHAR(255),
	koerperliche_Behinderung BOOLEAN,
	geistige_Behinderung BOOLEAN,
	seelische_Behinderung BOOLEAN,
	status VARCHAR(50),
	status_Datum VARCHAR(10),
	status_Grund VARCHAR(255),
	absagegrund VARCHAR(50),
	externe_Id VARCHAR(255),
	exportdatum VARCHAR(10),
	kibig_Id VARCHAR(255),
	anmeldedatum VARCHAR(10),
	voranmeldung_Gueltig_Bis VARCHAR(10),
	erstvorstellung VARCHAR(10),
	persoenlich_Vorgestellt BOOLEAN,
	betreuungswunsch_Ab VARCHAR(10),
	betreuungswunsch_Zeit VARCHAR(50),
	betreuungsform VARCHAR(50),
	prio_Warteliste BIGINT,
	platzart VARCHAR(50),
	anmeldecode VARCHAR(255),
	integrativplatz_Gewuenscht BOOLEAN,
	platzsharing_Gewuenscht BOOLEAN,
	betreuungszeit_Von BIGINT,
	betreuungszeit_Bis BIGINT,
	bemerkungen_Zur_Bewerbung VARCHAR(255),
	wechselkind BOOLEAN,
	wechselkind_Angabe_Eltern BOOLEAN,
	prio_Eltern BIGINT,
	schulbezirk_Id BIGINT,
	jahrgangsstufe_Id BIGINT,
	umzug_In_Schulbezirk_Zum VARCHAR(10),
	gastschulantrag_Gestellt BOOLEAN,
	vertragsbeginn VARCHAR(10),
	erster_Betreuungstag VARCHAR(10),
	kuendigungsdatum VARCHAR(10),
	vertragsende VARCHAR(10),
	vertragsende_Spaetestens VARCHAR(10),
	einschulungstermin VARCHAR(10),
	auswaertig BOOLEAN,
	umzug_Geplant BOOLEAN,
	auswaertig_Seit VARCHAR(10),
	auswaertig_Bis VARCHAR(10),
	auswaertig_Gefoerdert BOOLEAN,
	ausflugsfoerderung_Von VARCHAR(10),
	ausflugsfoerderung_Bis VARCHAR(10),
	but_Id VARCHAR(255),
	but_Verwendungszweck VARCHAR(50),
	kita_Id BIGINT,
	kita_Name VARCHAR(255),
	kita_Kibig_Id VARCHAR(255),
	
	sb1_id INTEGER,
	sb2_id INTEGER,
	
	PRIMARY KEY(ID, EXPORT_ID),
    CONSTRAINT FK_KIND
    	FOREIGN KEY(KIND_ID, EXPORT_ID)
        REFERENCES KIND(ID, EXPORT_ID),
    CONSTRAINT FK_SB1
    	FOREIGN KEY(SB1_ID, EXPORT_ID)
        REFERENCES SORGEBERECHTIGTER(ID, EXPORT_ID),
    CONSTRAINT FK_SB2
    	FOREIGN KEY(SB2_ID, EXPORT_ID)
        REFERENCES SORGEBERECHTIGTER(ID, EXPORT_ID)
);

CREATE TABLE BEWERBUNG (
	ID BIGINT,
	EXPORT_ID BIGINT,
	
	PRIMARY KEY(ID, EXPORT_ID),
    CONSTRAINT FK_KINDDATEN
    	FOREIGN KEY(ID, EXPORT_ID)
        REFERENCES KINDDATEN(ID, EXPORT_ID)
);

CREATE TABLE VERTRAG (
	ID BIGINT,
	EXPORT_ID BIGINT,
	
	PRIMARY KEY(ID, EXPORT_ID),
    CONSTRAINT FK_KINDDATEN
    	FOREIGN KEY(ID, EXPORT_ID)
        REFERENCES KINDDATEN(ID, EXPORT_ID)
);

CREATE TABLE BESONDERE_LAGE (
	ID BIGINT,
	EXPORT_ID BIGINT,
	BESONDERE_LAGE_ID BIGINT,
	
	PRIMARY KEY(ID, EXPORT_ID, BESONDERE_LAGE_ID)
);

CREATE TABLE ELTERNPRIORITAETSGRUND (
	ID BIGINT,
	EXPORT_ID BIGINT,
	ELTERNPRIORITAETSGRUND_ID BIGINT,
	
	PRIMARY KEY(ID, EXPORT_ID, ELTERNPRIORITAETSGRUND_ID)
);

CREATE TABLE ALTERSGRUPPEN (
	KINDDATEN_ID BIGINT,
	EXPORT_ID BIGINT,
	ID BIGINT,
	GUELTIG_VON VARCHAR(50),
	GUELTIG_BIS VARCHAR(50),
	
	PRIMARY KEY(KINDDATEN_ID, EXPORT_ID, ID)
);

CREATE TABLE EVENT (
	ID BIGINT,
	TIMESTAMP TIMESTAMP,
	TYPE VARCHAR(20),
	
	KIND_ID BIGINT,
	VERTRAG_ID BIGINT,
	EXPORT_ID BIGINT,
	
	PRIMARY KEY(ID)
);

CREATE TABLE OUTBOXEVENT (
	id UUID,
	timestamp timestamp,
	aggregate_id BIGINT,
	aggregate_type varchar(255),
	type varchar(255),
	state varchar(255),
	payload JSONB,
	error_message TEXT,
	retry_count BIGINT,
	retry_not_before TIMESTAMP,
	
	PRIMARY KEY(ID)
);


CREATE TABLE EXPORT_ERROR (
	ID BIGINT,
	EXPORT_ID BIGINT,
	TIMESTAMP TIMESTAMP,
	ERROR_MESSAGE VARCHAR(2000),
	
	PRIMARY KEY(ID, EXPORT_ID),
    CONSTRAINT FK_EXPORT
    	FOREIGN KEY(EXPORT_ID)
        REFERENCES EXPORT_RUN(ID)
);

CREATE OR REPLACE VIEW KIND_AKTUELL AS
	SELECT DISTINCT ON (ID) *
	FROM KIND
	ORDER BY ID, TIMESTAMP DESC;