CREATE SEQUENCE EXPORT_ID_SEQUENCE START 1;
CREATE SEQUENCE EVENT_ID_SEQUENCE START 1;

CREATE TABLE EXPORT_RUN (
	ID BIGINT,
	START_TIME TIMESTAMP,
	END_TIME TIMESTAMP,
	STATUS VARCHAR(50),
	
	PRIMARY KEY(ID)
);

CREATE TABLE KINDMAPPE_ID (
	ID BIGINT
);

CREATE TABLE KIND (
	ID BIGINT,
	EXPORT_ID BIGINT,
	TIMESTAMP TIMESTAMP,
	
	MASTERKIND_ID BIGINT,
	
	PRIMARY KEY(ID, EXPORT_ID),
    CONSTRAINT FK_EXPORT
    	FOREIGN KEY(EXPORT_ID)
        REFERENCES EXPORT_RUN(ID)
);

CREATE TABLE SORGEBERECHTIGTER (
    ID BIGINT,
    EXPORT_ID BIGINT,
    
    ANREDE VARCHAR(255),
    TITEL VARCHAR(255),
    VORNAME VARCHAR(255),
    NACHNAME VARCHAR(255),
    STRASSE VARCHAR(255),
    HAUSNUMMER VARCHAR(50),
    PLZ VARCHAR(20),
    ORT VARCHAR(255),
    LAND VARCHAR(255),
    TELEFON1 VARCHAR(50),
    TELEFON2 VARCHAR(50),
    EMAIL VARCHAR(255),
    AUSLAENDISCHEHERKUNFT BOOLEAN,
    NICHT_DEUTSCHSPRACHIGE_HERKUNFT BOOLEAN,
    ALLEIN_ERZIEHEND BOOLEAN,
    GEPLANTE_AUFNAHME_BERUFSTAETIGKEIT BOOLEAN,
    GEPLANTE_AUFNAHME_BERUFSTAETIGKEIT_AB DATE,
    GEPLANT_AUFNAHME_AUSBILDUNG BOOLEAN,
    GEPLANT_AUFNAHME_AUSBILDUNG_AB DATE,
    GEPLANT_AUFNAHME_STUDIUM BOOLEAN,
    GEPLANT_AUFNAHME_STUDIUM_AB DATE,
    BERUFSTAETIG BOOLEAN,
    ERST_STUDIUM_AUSBILDUNG BOOLEAN,
    WOCHENARBEITSZEIT DOUBLE PRECISION,
    WOCHENARBEITSTAGE DOUBLE PRECISION,
    LAGE_DER_ARBEITSZEIT_ID INTEGER,
    ARBEITSUCHEND BOOLEAN,
    ARBEITSUCHEND_SEIT DATE,
    
    PRIMARY KEY (ID, EXPORT_ID)
);

CREATE TABLE KINDDATEN (
	KIND_ID BIGINT,
	ID BIGINT,
	EXPORT_ID BIGINT,
	KINDAKTENTYP VARCHAR(50),
	
	VORNAME VARCHAR(255),
	NACHNAME VARCHAR(255),
	GEBURTSDATUM VARCHAR(255),
	geschlecht VARCHAR(50),
	pflegekind BOOLEAN,
	immunisierung_Masern VARCHAR(50),
	wohnhaft_Bei VARCHAR(50),
	familiensprache VARCHAR(255),
	weitere_Familiensprachen VARCHAR(255),
	koerperliche_Behinderung BOOLEAN,
	geistige_Behinderung BOOLEAN,
	seelische_Behinderung BOOLEAN,
	status VARCHAR(50),
	status_Datum DATE,
	status_Grund VARCHAR(255),
	absagegrund VARCHAR(50),
	externe_Id VARCHAR(255),
	exportdatum DATE,
	kibig_Id VARCHAR(255),
	anmeldedatum DATE,
	voranmeldung_Gueltig_Bis DATE,
	erstvorstellung DATE,
	persoenlich_Vorgestellt BOOLEAN,
	betreuungswunsch_Ab DATE,
	betreuungswunsch_Zeit VARCHAR(50),
	betreuungsform VARCHAR(50),
	prio_Warteliste BIGINT,
	platzart VARCHAR(50),
	anmeldecode VARCHAR(255),
	integrativplatz_Gewuenscht BOOLEAN,
	platzsharing_Gewuenscht BOOLEAN,
	betreuungszeit_Von BIGINT,
	betreuungszeit_Bis BIGINT,
	bemerkungen_Zur_Bewerbung VARCHAR(255),
	wechselkind BOOLEAN,
	wechselkind_Angabe_Eltern BOOLEAN,
	prio_Eltern BIGINT,
	schulbezirk_Id BIGINT,
	jahrgangsstufe_Id BIGINT,
	umzug_In_Schulbezirk_Zum DATE,
	gastschulantrag_Gestellt BOOLEAN,
	vertragsbeginn DATE,
	erster_Betreuungstag DATE,
	kuendigungsdatum DATE,
	vertragsende DATE,
	vertragsende_Spaetestens DATE,
	einschulungstermin DATE,
	auswaertig BOOLEAN,
	umzug_Geplant BOOLEAN,
	auswaertig_Seit DATE,
	auswaertig_Bis DATE,
	auswaertig_Gefoerdert BOOLEAN,
	ausflugsfoerderung_Von DATE,
	ausflugsfoerderung_Bis DATE,
	but_Id VARCHAR(255),
	but_Verwendungszweck VARCHAR(50),
	kita_Id BIGINT,
	kita_Name VARCHAR(255),
	kita_Kibig_Id VARCHAR(255),
	
	sb1_id INTEGER,
	sb2_id INTEGER,
	
	PRIMARY KEY(ID, EXPORT_ID),
    CONSTRAINT FK_KIND
    	FOREIGN KEY(KIND_ID, EXPORT_ID)
        REFERENCES KIND(ID, EXPORT_ID),
    CONSTRAINT FK_SB1
    	FOREIGN KEY(SB1_ID, EXPORT_ID)
        REFERENCES SORGEBERECHTIGTER(ID, EXPORT_ID),
    CONSTRAINT FK_SB2
    	FOREIGN KEY(SB2_ID, EXPORT_ID)
        REFERENCES SORGEBERECHTIGTER(ID, EXPORT_ID)
);

CREATE TABLE BEWERBUNG (
	ID BIGINT,
	EXPORT_ID BIGINT,
	
	PRIMARY KEY(ID, EXPORT_ID),
    CONSTRAINT FK_KINDDATEN
    	FOREIGN KEY(ID, EXPORT_ID)
        REFERENCES KINDDATEN(ID, EXPORT_ID)
);

CREATE TABLE VERTRAG (
	ID BIGINT,
	EXPORT_ID BIGINT,
	
	PRIMARY KEY(ID, EXPORT_ID),
    CONSTRAINT FK_KINDDATEN
    	FOREIGN KEY(ID, EXPORT_ID)
        REFERENCES KINDDATEN(ID, EXPORT_ID)
);

CREATE TABLE BESONDERE_LAGE (
	ID BIGINT,
	EXPORT_ID BIGINT,
	BESONDERE_LAGE_ID BIGINT,
	
	PRIMARY KEY(ID, EXPORT_ID, BESONDERE_LAGE_ID)
);

CREATE TABLE ELTERNPRIORITAETSGRUND (
	ID BIGINT,
	EXPORT_ID BIGINT,
	ELTERNPRIORITAETSGRUND_ID BIGINT,
	
	PRIMARY KEY(ID, EXPORT_ID, ELTERNPRIORITAETSGRUND_ID)
);

CREATE TABLE ALTERSGRUPPE (
	KINDDATEN_ID BIGINT,
	EXPORT_ID BIGINT,
	ID BIGINT,
	GUELTIG_VON DATE,
	GUELTIG_BIS DATE,
	
	PRIMARY KEY(KINDDATEN_ID, EXPORT_ID, ID)
);

CREATE TABLE BRING_ABHOLZEIT (
	KINDDATEN_ID BIGINT,
	EXPORT_ID BIGINT,
	ID BIGINT,
	GUELTIG_AB DATE,
	BRINGZEIT_MONTAG BIGINT,
	ABHOLZEIT_MONTAG BIGINT,
	BRINGZEIT_MONTAG2 BIGINT,
	ABHOLZEIT_MONTAG2 BIGINT,
	BRINGZEIT_DIENSTAG BIGINT,
	ABHOLZEIT_DIENSTAG BIGINT,
	BRINGZEIT_DIENSTAG2 BIGINT,
	ABHOLZEIT_DIENSTAG2 BIGINT,
	BRINGZEIT_MITTWOCH BIGINT,
	ABHOLZEIT_MITTWOCH BIGINT,
	BRINGZEIT_MITTWOCH2 BIGINT,
	ABHOLZEIT_MITTWOCH2 BIGINT,
	BRINGZEIT_DONNERSTAG BIGINT,
	ABHOLZEIT_DONNERSTAG BIGINT,
	BRINGZEIT_DONNERSTAG2 BIGINT,
	ABHOLZEIT_DONNERSTAG2 BIGINT,
	BRINGZEIT_FREITAG BIGINT,
	ABHOLZEIT_FREITAG BIGINT,
	BRINGZEIT_FREITAG2 BIGINT,
	ABHOLZEIT_FREITAG2 BIGINT,
	BRINGZEIT_SAMSTAG BIGINT,
	ABHOLZEIT_SAMSTAG BIGINT,
	BRINGZEIT_SAMSTAG2 BIGINT,
	ABHOLZEIT_SAMSTAG2 BIGINT,
	BRINGZEIT_SONNTAG BIGINT,
	ABHOLZEIT_SONNTAG BIGINT,
	BRINGZEIT_SONNTAG2 BIGINT,
	ABHOLZEIT_SONNTAG2 BIGINT,
	
	PRIMARY KEY(KINDDATEN_ID, EXPORT_ID, ID)
);

CREATE TABLE GRUPPE (
	KINDDATEN_ID BIGINT,
	EXPORT_ID BIGINT,
	GRUPPE_ID BIGINT,
	ZUORDNUNG_ID BIGINT,
	AB DATE,
	BIS DATE,
	GRUPPENNAME VARCHAR(255),
	
	PRIMARY KEY(KINDDATEN_ID, EXPORT_ID, GRUPPE_ID, ZUORDNUNG_ID)
);

CREATE TABLE INTEGRATION (
	KINDDATEN_ID BIGINT,
	EXPORT_ID BIGINT,
	ID BIGINT,
	GESTELLT VARCHAR(255),
	ABGELEHNT VARCHAR(255),
	VON DATE,
	BIS DATE,
	BEMERKUNG VARCHAR(255),
	BESCHEIDERLASSENDE_STELLE_ID BIGINT,
	GEWICHTUNGSFAKTOR_INTEGRATION BOOLEAN,
	
	PRIMARY KEY(KINDDATEN_ID, EXPORT_ID, ID)
);

CREATE TABLE KONTINGENT (
	KINDDATEN_ID BIGINT,
	EXPORT_ID BIGINT,
	ID BIGINT,
	VON DATE,
	BIS DATE,
	BEMERKUNG VARCHAR(255),
	
	PRIMARY KEY(KINDDATEN_ID, EXPORT_ID, ID)
);

CREATE TABLE VERTRAGSABSCHNITT (
	KINDDATEN_ID BIGINT,
	EXPORT_ID BIGINT,
	ID BIGINT,
	AB DATE,
	BIS DATE,
	BETREUUNGSZEIT_ID BIGINT,
	VERPFLEGUNG_ID BIGINT,
	KOERPERLICHE_BEHINDERUNG BOOLEAN,
	GEISTIGE_BEHINDERUNG BOOLEAN,
	SEELISCHE_BEHINDERUNG BOOLEAN,
	BRING_ABHOLZEIT_ID BIGINT,
	
	PRIMARY KEY(KINDDATEN_ID, EXPORT_ID, ID)
);

CREATE TABLE EVENT (
	ID BIGINT,
	TIMESTAMP TIMESTAMP,
	TYPE VARCHAR(20),
	
	KIND_ID BIGINT,
	VERTRAG_ID BIGINT,
	EXPORT_ID BIGINT,
	
	PRIMARY KEY(ID)
);

CREATE TABLE OUTBOXEVENT (
	id UUID,
	timestamp timestamp,
	aggregate_id BIGINT,
	aggregate_type varchar(255),
	type varchar(255),
	state varchar(255),
	payload JSONB,
	error_message TEXT,
	retry_count BIGINT,
	retry_not_before TIMESTAMP,
	
	PRIMARY KEY(ID)
);


CREATE TABLE EXPORT_ERROR (
	ID BIGINT,
	EXPORT_ID BIGINT,
	TIMESTAMP TIMESTAMP,
	ERROR_MESSAGE VARCHAR(2000),
	
	PRIMARY KEY(ID, EXPORT_ID),
    CONSTRAINT FK_EXPORT
    	FOREIGN KEY(EXPORT_ID)
        REFERENCES EXPORT_RUN(ID)
);

CREATE OR REPLACE VIEW KIND_AKTUELL AS
	SELECT DISTINCT ON (ID) *
	FROM KIND
	ORDER BY ID, TIMESTAMP DESC;