CREATE TYPE EXPORT_STATUS AS ENUM ('RUNNING', 'SUCCESS', 'ERROR');

CREATE SEQUENCE EXPORT_ID_SEQUENCE START 1;

CREATE TABLE EXPORT_RUN (
	ID BIGINT,
	START_TIME TIMESTAMP,
	END_TIME TIMESTAMP,
	STATUS EXPORT_STATUS,
	
	PRIMARY KEY(ID)
);

CREATE TABLE KINDMAPPE_ID (
	ID BIGINT
);

CREATE TABLE KIND (
	ID BIGINT,
	EXPORT_ID BIGINT,
	TIMESTAMP TIMESTAMP,
	
	VORNAME VARCHAR(255),
	NACHNAME VARCHAR(255),
	GEBURTSDATUM VARCHAR(255),
	
	KIND_AKTEN TEXT,
	
	PRIMARY KEY(ID, EXPORT_ID),
    CONSTRAINT FK_EXPORT
    	FOREIGN KEY(EXPORT_ID)
        REFERENCES EXPORT_RUN(ID)
);

CREATE TABLE EXPORT_ERROR (
	ID BIGINT,
	EXPORT_ID BIGINT,
	TIMESTAMP TIMESTAMP,
	ERROR_MESSAGE VARCHAR(2000),
	
	PRIMARY KEY(ID, EXPORT_ID),
    CONSTRAINT FK_EXPORT
    	FOREIGN KEY(EXPORT_ID)
        REFERENCES EXPORT_RUN(ID)
);

CREATE OR REPLACE VIEW KIND_AKTUELL AS
	SELECT DISTINCT ON (ID) *
	FROM KIND
	ORDER BY ID, TIMESTAMP DESC;