package de.muenchen.rbs.kitafinderdatenservice.domain;

public enum Absagegrund {
	// @formatter:off
	// Mapping works out of the box, as long as values are in the correct order
	UNBEKANNT,//0
	KEIN_BEDARF_MEHR,//1
	ABSAGE_DURCH_ELTERN,//2
	ABSAGE_DURCH_EINRICHTUNG,//3
	VERTRAGSVERGABE_ANDERE_EINRICHTUNG,//4
	UEBERGREIFENDE_ABSAGE_ANDERE_EINRICHTUNG,//5
	UEBERSCHRITTENER_BEWERBUNGSTERMIN,//6
	IMPORT_EXPORT,//7
	UEBERSCHREITUNG_ZUSAGEFRIST,//8
	ZUSAGE_ANDERE_EINRICHTUNG,//9
	ERNEUTE_BEWERBUNG,//10
	VORMERKUNG_ZURUECKGENOMMEN,//11
	ABSAGE_ELTERNBERATUNGSSTELLE,//12
	KINDDATENUEBERTRAGUNG_ANDERE_EINRICHTUNG,//13
	LOESCHEN_BENUTZERKONTO;//14
	// @formatter:on
}
