spring:
  application.name: kitafinder-datenservice-web

  profiles.active:
    - local

  docker:
    compose:
      enabled: false

app:
  security:
    sso-base-url: http://localhost:8100
    realm: KM23
    token-url: ${app.security.sso-base-url}/auth/realms/${app.security.realm}/protocol/openid-connect/token
    issuer-url: ${app.security.sso-base-url}/auth/realms/${app.security.realm}
    client-id: kitafinder-datenservice
---
spring:
  config:
    activate:
      on-profile: test
  flyway.clean-on-validation-error: true
  
  datasource:
    url: jdbc:tc:postgresql://localhost:5432/postgres
    username: postgres
    password: admin

---
spring:
  config:
    activate:
      on-profile: local
  flyway.clean-on-validation-error: true

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: admin
    password: admin
  docker:
    compose:
      enabled: true
      file: stack/docker-compose.yml

springdoc.show-actuator: true
