spring:
  application.name: kitafinder-datenservice-batch
  main.web-application-type: NONE

  profiles.active:
    - local

  docker:
    compose:
      enabled: false
  codec:
    max-in-memory-size: 16MB

  jpa.properties.hibernate:
    jdbc.batch_size: 500
    order_inserts: true
    order_updates: true

app:
  export.id: # override to restart a previous run
  log-intervall-pages: 20 
  kitafinder:
    base-url: http://kitafinder-plan-k3.muenchen.de/kitaplaner/api
    username: # provide locally
    password: # provide locally
    timeout-seconds: 30
    id-batch-size: 200
    data-batch-size: 50
    cleanup-keep-age: -1
    cleanup-keep-number: 0
---
spring:
  config:
    activate:
      on-profile: test
  
  datasource:
    url: jdbc:tc:postgresql://localhost:5432/postgres
    username: postgres
    password: admin

app.auto-close: false
---
spring:
  config:
    activate:
      on-profile: local

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: admin
    password: admin
  docker:
    compose:
      enabled: true
      file: stack/docker-compose.yml
